name: 'Restore and Test Database'
description: 'Check if database backup is valid'
inputs:
  config-path:  # id of input
    description: 'config path'
    required: true
    default: './config.yaml'
runs:
  using: docker
  image: ghcr.io/takutakahashi/database-restore-action:latest
  args:
    - -c
    - ${{ inputs.config-path }}
