name: 'Restore and Test Database'
description: 'Check if database backup is valid'
inputs:
  config-path:  # id of input
    description: 'config path'
    required: true
    default: './config.yaml'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
  args:
    - -c
    - ${{ inputs.config-path }}
