database:
  type: mysql
  name: test
  user: root
  password: root
  host: 127.0.0.1
  port: 33060
check:
- table: "test"
  column: "user"
  count_eq: 2 
backup:
  uri: file://./sample/test.dump
  local: ./sample/test.dump